server {
    listen 80;
    server_name localhost;

    client_max_body_size 50M; 
    # El root apunta directamente al directorio public de Laravel
    root /var/www/html/public;
    index index.php index.html index.htm;
  
    # Maneja todas las solicitudes con index.php
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Configuración para manejar archivos PHP
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        dav_methods PUT DELETE MKCOL COPY MOVE;
    }

    # Denegar el acceso a archivos .htaccess
    location ~ /\.ht {
        deny all;
    }
}
